name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev/server
<<<<<<< HEAD
      - dev/client
=======
>>>>>>> b1edb107fe96c4247fa84ab406f210cf76892d36

jobs:
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Change to Backend Directory
        run: cd server 

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./server

      - name: Run Backend Tests
        run: npm test
        working-directory: ./server  
  
